//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCRSocialNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClubComment
    {
        public int ClubCommentId { get; set; }
        public int ClubId { get; set; }
        public string ClubCommentDescription { get; set; }
        public int UserId { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual User User { get; set; }
    }
}
