//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCRSocialNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.EventComments = new HashSet<EventComment>();
            this.EventLikeDislikes = new HashSet<EventLikeDislike>();
            this.Users = new HashSet<User>();
            this.ClubEvents = new HashSet<ClubEvent>();
        }
    
        public int EventId { get; set; }
        public string EventTitle { get; set; }
        public int ClubId { get; set; }
        public string EventDescription { get; set; }
        public string EventVenue { get; set; }
        public System.DateTime EventDate { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual ICollection<EventComment> EventComments { get; set; }
        public virtual ICollection<EventLikeDislike> EventLikeDislikes { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<ClubEvent> ClubEvents { get; set; }
    }
}
