//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCRSocialNetwork.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NCRSocialNetworkDBEntities : DbContext
    {
        public NCRSocialNetworkDBEntities()
            : base("name=NCRSocialNetworkDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ClubComment> ClubComments { get; set; }
        public DbSet<Club> Clubs { get; set; }
        public DbSet<ClubSubscribtion> ClubSubscribtions { get; set; }
        public DbSet<EventComment> EventComments { get; set; }
        public DbSet<EventLikeDislike> EventLikeDislikes { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<ClubEvent> ClubEvents { get; set; }
    }
}
