//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCRSocialNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ClubComments = new HashSet<ClubComment>();
            this.EventComments = new HashSet<EventComment>();
            this.EventLikeDislikes = new HashSet<EventLikeDislike>();
            this.Clubs = new HashSet<Club>();
            this.Events = new HashSet<Event>();
        }
    
        public int UserId { get; set; }
        public string UserFirstName { get; set; }
    
        public virtual ICollection<ClubComment> ClubComments { get; set; }
        public virtual ICollection<EventComment> EventComments { get; set; }
        public virtual ICollection<EventLikeDislike> EventLikeDislikes { get; set; }
        public virtual ICollection<Club> Clubs { get; set; }
        public virtual ICollection<Event> Events { get; set; }
    }
}
